# Generated by Django 5.1.5 on 2025-06-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'permissions': [('can_add_game', 'Can add game'), ('can_delete_game', 'Can delete game'), ('can_edit_game', 'Can edit game')]},
        ),
    ]
