# Generated by Django 5.1.5 on 2025-09-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_order_currency_order_has_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='default', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='zip',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
