# Generated by Django 5.1.5 on 2025-09-15 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_order_email_order_full_name_order_notes_order_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='games',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.order')),
            ],
        ),
    ]
