# Generated by Django 5.1.5 on 2025-09-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_remove_order_count_remove_order_games_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
    ]
